// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 687);
    lv_obj_set_height(ui_Panel2, 323);
    lv_obj_set_x(ui_Panel2, 15);
    lv_obj_set_y(ui_Panel2, -1);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_On_button = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_On_button, 100);
    lv_obj_set_height(ui_On_button, 100);
    lv_obj_set_x(ui_On_button, -200);
    lv_obj_set_y(ui_On_button, 0);
    lv_obj_set_align(ui_On_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_On_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_On_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_On_button_label = lv_label_create(ui_On_button);
    lv_obj_set_width(ui_On_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_On_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_On_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_On_button_label, "ON");
    lv_obj_set_style_text_color(ui_On_button_label, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_On_button_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_On_button_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Off_button = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_Off_button, 100);
    lv_obj_set_height(ui_Off_button, 100);
    lv_obj_set_x(ui_Off_button, 516);
    lv_obj_set_y(ui_Off_button, 59);
    lv_obj_set_align(ui_Off_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Off_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Off_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Off_button_label = lv_label_create(ui_Off_button);
    lv_obj_set_width(ui_Off_button_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Off_button_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Off_button_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Off_button_label, "OFF");
    lv_obj_set_style_text_color(ui_Off_button_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Off_button_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Off_button_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RECbutton = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_RECbutton, 100);
    lv_obj_set_height(ui_RECbutton, 100);
    lv_obj_set_x(ui_RECbutton, -18);
    lv_obj_set_y(ui_RECbutton, -90);
    lv_obj_set_align(ui_RECbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RECbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RECbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RECbutton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RECbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_RECbutton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "O REC");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_On_button, ui_event_On_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Off_button, ui_event_Off_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RECbutton, ui_event_RECbutton, LV_EVENT_ALL, NULL);

}
