// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
void ui_event_ScreenCapture(lv_event_t * e);
extern lv_obj_t * ui_ScreenCapture;
void ui_event_ScreenRecordButton(lv_event_t * e);
extern lv_obj_t * ui_ScreenRecordButton;
void ui_event_AmdsidebarButton(lv_event_t * e);
extern lv_obj_t * ui_AmdsidebarButton;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_screenshot_png);    // assets\screenshot.png
LV_IMG_DECLARE(ui_img_815904853);    // assets\recording (1).png
LV_IMG_DECLARE(ui_img_577774466);    // assets\amd (1).png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
