// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Macropad0.0.2

#ifndef _MACROPAD0_0_2_UI_H
#define _MACROPAD0_0_2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
void ui_event_ScreenCapture(lv_event_t * e);
extern lv_obj_t * ui_ScreenCapture;
void ui_event_ScreenRecordButton(lv_event_t * e);
extern lv_obj_t * ui_ScreenRecordButton;
void ui_event_AmdsidebarButton(lv_event_t * e);
extern lv_obj_t * ui_AmdsidebarButton;
extern lv_obj_t * ui_Panel3;
void ui_event_macroscreenButton1(lv_event_t * e);
extern lv_obj_t * ui_macroscreenButton1;
void ui_event_lightscreenButton1(lv_event_t * e);
extern lv_obj_t * ui_lightscreenButton1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel5;
void ui_event_MinusBrightnessButton(lv_event_t * e);
extern lv_obj_t * ui_MinusBrightnessButton;
void ui_event_SwitchLightButton(lv_event_t * e);
extern lv_obj_t * ui_SwitchLightButton;
void ui_event_PlusLightButton(lv_event_t * e);
extern lv_obj_t * ui_PlusLightButton;
extern lv_obj_t * ui_Panel6;
void ui_event_macroscreenButton2(lv_event_t * e);
extern lv_obj_t * ui_macroscreenButton2;
void ui_event_lightscreenButton2(lv_event_t * e);
extern lv_obj_t * ui_lightscreenButton2;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_screenshot_png);    // assets\screenshot.png
LV_IMG_DECLARE(ui_img_815904853);    // assets\recording (1).png
LV_IMG_DECLARE(ui_img_577774466);    // assets\amd (1).png
LV_IMG_DECLARE(ui_img_1080249043);    // assets\virus-scan.png
LV_IMG_DECLARE(ui_img_1704086984);    // assets\light-bulb.png
LV_IMG_DECLARE(ui_img_1714697232);    // assets\minus (1).png
LV_IMG_DECLARE(ui_img_877206327);    // assets\lightbulb (1).png
LV_IMG_DECLARE(ui_img_lightbulb_png);    // assets\lightbulb.png
LV_IMG_DECLARE(ui_img_add_png);    // assets\add.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
