// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Macropad0.0.2

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ScreenCaptureButton(lv_event_t * e);
void ScreenRecord(lv_event_t * e);
void AMDsidebar(lv_event_t * e);
void LowerbrightnessButton(lv_event_t * e);
void SwitchLightButton(lv_event_t * e);
void upbrightnessButton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
