// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "USBKeyboard.h"
#include "PluggableUSBHID.h"

USBKeyboard Keyboard;


void ScreenCaptureButton(lv_event_t * e)
{
	// Your code here
	Keyboard.key_code('i', KEY_CTRL | KEY_SHIFT);
}

void ScreenRecord(lv_event_t * e)
{
	// Your code here
	Keyboard.key_code('e', KEY_CTRL | KEY_SHIFT);
}

void AMDsidebar(lv_event_t * e)
{
	// Your code here
	Keyboard.key_code('a', KEY_ALT);
}




