// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "PluggableUSBHID.h"
#include "USBKeyboard.h"


void Onbutton(lv_event_t * e)
{
	// Your code here
}

void Offbutton(lv_event_t * e)
{
	// Your code here
}

void RecordControl(lv_event_t * e)
{


}
