// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Macropad0.0.2

#ifndef _UI_COMP_SIDEBAR_H
#define _UI_COMP_SIDEBAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Sidebar
#define UI_COMP_SIDEBAR_SIDEBAR 0
#define UI_COMP_SIDEBAR_MACROSCREENBUTTON 1
#define UI_COMP_SIDEBAR_LIGHTSCREENBUTTON 2
#define _UI_COMP_SIDEBAR_NUM 3
lv_obj_t * ui_Sidebar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
