// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Macropad0.0.2

#include "../ui.h"


// COMPONENT Sidebar

lv_obj_t * ui_Sidebar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Sidebar;
    cui_Sidebar = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Sidebar, 100);
    lv_obj_set_height(cui_Sidebar, 400);
    lv_obj_set_x(cui_Sidebar, -340);
    lv_obj_set_y(cui_Sidebar, 0);
    lv_obj_set_align(cui_Sidebar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Sidebar, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Sidebar, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Sidebar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_macroscreenButton;
    cui_macroscreenButton = lv_imgbtn_create(cui_Sidebar);
    lv_imgbtn_set_src(cui_macroscreenButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1080249043, NULL);
    lv_obj_set_width(cui_macroscreenButton, 80);
    lv_obj_set_height(cui_macroscreenButton, 80);
    lv_obj_set_x(cui_macroscreenButton, 12);
    lv_obj_set_y(cui_macroscreenButton, -81);
    lv_obj_set_align(cui_macroscreenButton, LV_ALIGN_CENTER);

    lv_obj_t * cui_lightscreenButton;
    cui_lightscreenButton = lv_imgbtn_create(cui_Sidebar);
    lv_imgbtn_set_src(cui_lightscreenButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1704086984, NULL);
    lv_obj_set_width(cui_lightscreenButton, 80);
    lv_obj_set_height(cui_lightscreenButton, 80);
    lv_obj_set_x(cui_lightscreenButton, -1706);
    lv_obj_set_y(cui_lightscreenButton, -14);
    lv_obj_set_align(cui_lightscreenButton, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SIDEBAR_NUM);
    children[UI_COMP_SIDEBAR_SIDEBAR] = cui_Sidebar;
    children[UI_COMP_SIDEBAR_MACROSCREENBUTTON] = cui_macroscreenButton;
    children[UI_COMP_SIDEBAR_LIGHTSCREENBUTTON] = cui_lightscreenButton;
    lv_obj_add_event_cb(cui_Sidebar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Sidebar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Sidebar_create_hook(cui_Sidebar);
    return cui_Sidebar;
}

