// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Onbutton(lv_event_t * e);
void Offbutton(lv_event_t * e);
void Trymeany(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
