// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void AMDButton(lv_event_t * e)
{
	// Your code here
}

void ScreenCaptureButton(lv_event_t * e)
{
	// Your code here
}

void ScreenRecord(lv_event_t * e)
{
	// Your code here
}

void AMDsidebar(lv_event_t * e)
{
	// Your code here
}

void LowerbrightnessButton(lv_event_t * e)
{
	// Your code here
}

void SwitchLightButton(lv_event_t * e)
{
	// Your code here
}

void upbrightnessButton(lv_event_t * e)
{
	// Your code here
}
