// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Macropad0.0.2

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 560);
    lv_obj_set_height(ui_Panel2, 360);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xAFAFC1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenCapture = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_ScreenCapture, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_screenshot_png, NULL);
    lv_obj_set_width(ui_ScreenCapture, 80);
    lv_obj_set_height(ui_ScreenCapture, 80);
    lv_obj_set_align(ui_ScreenCapture, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_img_src(ui_ScreenCapture, &ui_img_screenshot_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenRecordButton = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_ScreenRecordButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_815904853, NULL);
    lv_obj_set_width(ui_ScreenRecordButton, 80);
    lv_obj_set_height(ui_ScreenRecordButton, 80);
    lv_obj_set_align(ui_ScreenRecordButton, LV_ALIGN_CENTER);

    ui_AmdsidebarButton = lv_imgbtn_create(ui_Panel2);
    lv_imgbtn_set_src(ui_AmdsidebarButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_577774466, NULL);
    lv_obj_set_width(ui_AmdsidebarButton, 80);
    lv_obj_set_height(ui_AmdsidebarButton, 80);
    lv_obj_set_x(ui_AmdsidebarButton, -102);
    lv_obj_set_y(ui_AmdsidebarButton, -71);
    lv_obj_set_align(ui_AmdsidebarButton, LV_ALIGN_CENTER);

    ui_Panel4 = ui_Sidebar_create(ui_Screen1);
    lv_obj_set_x(ui_Panel4, -340);
    lv_obj_set_y(ui_Panel4, 0);



    lv_obj_add_event_cb(ui_ScreenCapture, ui_event_ScreenCapture, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenRecordButton, ui_event_ScreenRecordButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AmdsidebarButton, ui_event_AmdsidebarButton, LV_EVENT_ALL, NULL);

}
