// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Macropad0.0.2

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel1, 560);
    lv_obj_set_height(ui_Panel1, 360);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xAFAFC1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel5, 120);
    lv_obj_set_height(ui_Panel5, 300);
    lv_obj_set_x(ui_Panel5, -1);
    lv_obj_set_y(ui_Panel5, 0);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_COLUMN_REVERSE);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFECAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinusBrightnessButton = lv_imgbtn_create(ui_Panel5);
    lv_imgbtn_set_src(ui_MinusBrightnessButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1714697232, NULL);
    lv_obj_set_width(ui_MinusBrightnessButton, 80);
    lv_obj_set_height(ui_MinusBrightnessButton, 80);
    lv_obj_set_align(ui_MinusBrightnessButton, LV_ALIGN_CENTER);

    ui_SwitchLightButton = lv_imgbtn_create(ui_Panel5);
    lv_imgbtn_set_src(ui_SwitchLightButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_877206327, NULL);
    lv_imgbtn_set_src(ui_SwitchLightButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lightbulb_png, NULL);
    lv_obj_set_width(ui_SwitchLightButton, 80);
    lv_obj_set_height(ui_SwitchLightButton, 80);
    lv_obj_set_align(ui_SwitchLightButton, LV_ALIGN_CENTER);

    ui_PlusLightButton = lv_imgbtn_create(ui_Panel5);
    lv_imgbtn_set_src(ui_PlusLightButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_png, NULL);
    lv_obj_set_width(ui_PlusLightButton, 80);
    lv_obj_set_height(ui_PlusLightButton, 80);
    lv_obj_set_align(ui_PlusLightButton, LV_ALIGN_CENTER);

    ui_Panel6 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel6, 100);
    lv_obj_set_height(ui_Panel6, 400);
    lv_obj_set_x(ui_Panel6, -340);
    lv_obj_set_y(ui_Panel6, 0);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_macroscreenButton2 = lv_imgbtn_create(ui_Panel6);
    lv_imgbtn_set_src(ui_macroscreenButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1080249043, NULL);
    lv_obj_set_width(ui_macroscreenButton2, 80);
    lv_obj_set_height(ui_macroscreenButton2, 80);
    lv_obj_set_x(ui_macroscreenButton2, 12);
    lv_obj_set_y(ui_macroscreenButton2, -81);
    lv_obj_set_align(ui_macroscreenButton2, LV_ALIGN_CENTER);

    ui_lightscreenButton2 = lv_imgbtn_create(ui_Panel6);
    lv_imgbtn_set_src(ui_lightscreenButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_1704086984, NULL);
    lv_obj_set_width(ui_lightscreenButton2, 80);
    lv_obj_set_height(ui_lightscreenButton2, 80);
    lv_obj_set_x(ui_lightscreenButton2, -1706);
    lv_obj_set_y(ui_lightscreenButton2, -14);
    lv_obj_set_align(ui_lightscreenButton2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_MinusBrightnessButton, ui_event_MinusBrightnessButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchLightButton, ui_event_SwitchLightButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlusLightButton, ui_event_PlusLightButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_macroscreenButton2, ui_event_macroscreenButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightscreenButton2, ui_event_lightscreenButton2, LV_EVENT_ALL, NULL);

}
